### ISSUE TITLE
Importing ceylon.logging causes compiler error

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#481]
Attempting to compile a module with:

```ceylon
module com.example.helloworld "1.0.0" {
    import ceylon.logging "1.1.1";
}
```

results in:

```
ceylon compile-js: null
java.lang.NullPointerException
        at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:732)
        at com.redhat.ceylon.compiler.loader.JsonPackage.loadAttribute(JsonPackage.java:497)
        at com.redhat.ceylon.compiler.loader.JsonPackage.addAttributesAndMethods(JsonPackage.java:244)
        at com.redhat.ceylon.compiler.loader.JsonPackage.loadInterface(JsonPackage.java:600)
        at com.redhat.ceylon.compiler.loader.JsonPackage.load(JsonPackage.java:923)
        at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:827)
        at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:860)
        at com.redhat.ceylon.compiler.loader.JsonPackage.loadAttribute(JsonPackage.java:497)
        at com.redhat.ceylon.compiler.loader.JsonPackage.loadDeclarations(JsonPackage.java:115)
        at com.redhat.ceylon.compiler.loader.JsonModule.loadDeclarations(JsonModule.java:54)
        at com.redhat.ceylon.compiler.loader.JsModuleManager.loadModuleFromMap(JsModuleManager.java:198)
        at com.redhat.ceylon.compiler.loader.JsModuleManager.resolveModule(JsModuleManager.java:89)
        at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:210)
        at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:216)
        at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:86)
        at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:149)
        at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:127)
        at com.redhat.ceylon.compiler.js.CeylonCompileJsTool.run(CeylonCompileJsTool.java:319)
        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:368)
        at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:305)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
        at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
```

**Comment by chochos** [comment]
Huh, interface `Logger` has an alias called `Message` which is being loaded as an attribute. Never thought to test member type aliases before.
