### ISSUE TITLE
Error using unqualified class property in named constructor

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#484]
Accessing a property without qualifying with `this` does not work inside named constructors.

```ceylon
shared void run(){
    value foo = Foo.Default();
}

class Foo { 
  Integer someInt;
  shared new Default() {
      this.someInt = 1;
      print(this.someInt + 1); // prints 2
      print(someInt + 1);      // error
  }
}
```

results in:

```
/Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:24
    m$1.print(Foo.$3.plus(1));
                     ^
TypeError: Cannot call method 'plus' of undefined
    at Foo_Default (/Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:24:22)
    at run (/Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:11:12)
    at [eval]:1:318
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
this is a scoping issue similar to several ones I've had with constructors. Shouldn't be hard to fix.
