### ISSUE TITLE
Named constructor not visible by default within class definition

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#485]
Named constructors are not available within a class definition without being qualified with the class name:

```ceylon
shared void run(){
  print(CTest.DefaultCtor().clone1()); // works
  print(CTest.DefaultCtor().clone2()); // error
}

shared class CTest {
  shared new DefaultCtor() { }

  shared CTest clone1() {
    return CTest.DefaultCtor();
  }

  shared CTest clone2() {
    return DefaultCtor();
  }
}
```

Results in:

```
$ ceylonDev compile-js && ceylonDev run-js com.example.simple
Note: Created module com.example.simple/1.0.0
com.example.simple::CTest@1

/Users/jvasileff/Desktop/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:40
                return cTest$_DefaultCtor();
                       ^
ReferenceError: cTest$_DefaultCtor is not defined
    at $init$CTest.cTest$.clone2 (/Users/jvasileff/Desktop/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:40:24)
    at run (/Users/jvasileff/Desktop/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:12:35)
    at [eval]:1:318
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
while adding tests for this I may have stumbled onto a typechecker bug, see ceylon/ceylons-spec#1195
