### ISSUE TITLE
Errors with arguments declared in body of curried function

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#503]
This:

```ceylon
shared void crtest() {
    void runner(run)() {
        Anything() run;
        run();
    }
    runner(()=>print("x"))();
}
```

Results in:

```
/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:410
            $r5k();
            ^
TypeError: undefined is not a function
    at Number.$r5j.$r5l (/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:410:13)
    at JsCallable.f2 (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150219-2054/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:631:10)
    at crtest (/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:416:84)
    at [eval]:1:348
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

Possibly related to #486?

These variations work:

```ceylon
    void runner2(run)() {
        Anything run();
        run();
    }
    runner2(()=>print("x"))();    

    void runner3(Anything run())() => run();
    runner3(()=>print("x"))();    

    void runner4(Anything() run)() => run();
    runner4(()=>print("x"))();
```

**Comment by jvasileff** [comment]
Actually, the issue looks more general:

```ceylon
    void runner6(x)() {
        String x;
        print(x);
    }
    runner6("javascript")();
```

prints `<null>` instead of `javascript`.

**Comment by chochos** [comment]
No relation to the other issue at all. This is caused by the way `x` is declared. `void runner6(String x)` works fine.
