### ISSUE TITLE
bug in default argument inheritance

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#504]
Given:

```ceylon
shared void run() {
    C().m();
}

class C() satisfies L5 {
    shared actual void m(Integer i) => print("hello");
}

interface L5 satisfies L4 {
    shared actual formal void m(Integer i);
}


interface L3 satisfies L2 {
    shared actual formal void m(Integer i);
}

interface L1 {
    shared formal void m(Integer i=1);
}

interface L2 satisfies L1 {
    shared actual formal void m(Integer i);
}

interface L4 satisfies L3 {
    shared actual formal void m(Integer i);
}
```

I get:

```
/Users/gavin/Documents/workspace/js/modules/default/default.js:31
                if($3k===undefined){$3k=c$.m$defs$i($3k);}
                                           ^
TypeError: undefined is not a function
    at c$.m (/Users/gavin/Documents/workspace/js/modules/default/default.js:31:44)
    at run (/Users/gavin/Documents/workspace/js/modules/default/default.js:11:9)
    at [eval]:1:267
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```

Writing in the argument makes the error go away.

**Comment by gavinking** [comment]
Thanks
