### ISSUE TITLE
Cannot call method 'annotations' of undefined

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon-js#515]
When running SDK tests ...
```
test-js:
[ceylon-test-js] NODE_PATH=/Users/thradec/workspace/ceylon/ceylon-dist/dist/repo:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/test-deps:/Users/thradec/.ceylon/repo:/Users/thradec/.ceylon/cache:[Maven] Aether:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules:/Users/thradec/workspace/ceylon/ceylon-sdk/modules
[ceylon-test-js] 
[ceylon-test-js] /Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1286
[ceylon-test-js]             $39p=$39n.containingPackage.annotations({Annotation$annotations:$$
[ceylon-test-js]                                         ^
[ceylon-test-js] TypeError: Cannot call method 'annotations' of undefined
[ceylon-test-js]     at findAnnotation$core (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1286:41)
[ceylon-test-js]     at createExecutor$core (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:981:14)
[ceylon-test-js]     at createExecutors$core (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:942:26)
[ceylon-test-js]     at $init$DefaultTestRunner$core.defaultTestRunner$.$357 (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:871:24)
[ceylon-test-js]     at DefaultTestRunner$core (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:836:49)
[ceylon-test-js]     at Object.createTestRunner (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2262:12)
[ceylon-test-js]     at run (/Users/thradec/workspace/ceylon/ceylon-sdk/modules/com/redhat/ceylon/testjs/1.1.1/com.redhat.ceylon.testjs-1.1.1.js:197:20)
[ceylon-test-js]     at [eval]:1:336
[ceylon-test-js]     at Object.<anonymous> ([eval]-wrapper:6:22)
[ceylon-test-js]     at Module._compile (module.js:456:26)
```

**Comment by thradec** [comment]
Thanks!
