### ISSUE TITLE
cannot extend default constructor that takes a parameter

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#536]
For:

```ceylon
class Ec {
    shared new (String _) {
        print("In Default");
    }

    shared new Alt() extends Ec("") {
        print("In Alt");
    }
}
```

you get a runtime error when invoking `Ec.Alt()`:

```
/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:1223
Ec$$a("",ec$);
^
ReferenceError: Ec$$a is not defined
    at Ec_Alt (/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:1223:1)
    at testEc (/Users/jvasileff/Dropbox/Repos/jv/sandbox-ceylon-snapjs/modules/sandbox/ceylon/snapjs/base/0.0.1/sandbox.ceylon.snapjs.base-0.0.1.js:1245:1)
    at [eval]:1:348
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```

**Comment by chochos** [comment]
Actually this fails with any constructors that delegate to the default constructor, regardless of args.

**Comment by jvasileff** [comment]
Oh, yeah, sorry. I think it may have been on the JVM side where I saw some differences with args.

On May 4, 2015, at 12:25 PM, Enrique Zamudio <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually this fails with any constructors that delegate to the default constructor, regardless of args.
