### ISSUE TITLE
StackOverflowError in TypeUtils.typeContainsTypeParameter()

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-js#542]
Code is in the [js-error branch](https://github.com/tombentley/ceylon-sdk/tree/js-error) in my fork of ceylon-sdk. The same code works fine with the JVM compiler, but with JS I get this

Caused by: java.lang.StackOverflowError
	at com.redhat.ceylon.compiler.typechecker.model.Util.isOverloadedVersion(Util.java:162)
	at com.redhat.ceylon.compiler.typechecker.model.Unit.getAbstraction(Unit.java:135)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getDeclaration(ProducedType.java:101)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getDeclaration(ProducedType.java:39)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedReference.getTypeArguments(ProducedReference.java:48)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSatisfiedTypes(ProducedType.java:1837)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:744)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:742)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:742)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:746)
	at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:730)
	at com.redhat.ceylon.compiler.js.util.TypeUtils.typeContainsTypeParameter(TypeUtils.java:365)
	at com.redhat.ceylon.compiler.js.util.TypeUtils.typeContainsTypeParameter(TypeUtils.java:367)
	at com.redhat.ceylon.compiler.js.util.TypeUtils.typeContainsTypeParameter(TypeUtils.java:367)
	at com.redhat.ceylon.compiler.js.util.TypeUtils.typeContainsTypeParameter(TypeUtils.java:367)
	at com.redhat.ceylon.compiler.js.util.TypeUtils.typeContainsTypeParameter(TypeUtils.java:367)

**Comment by chochos** [comment]
Is this still happening? I mean with all the model, typechecker and compiler changes lately...

**Comment by chochos** [comment]
@tombentley can you still reproduce this?

**Comment by tombentley** [comment]
Absolutely no idea, and given the lack of a small reproducible test case I think we should close it.
