### ISSUE TITLE
Invoking reference to class initializer creates instances with missing type information

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#545]
This:

```ceylon
shared void run() {
    Singleton<String>(String) singletonFactory = Singleton<String>;
    Singleton<String> ss = singletonFactory("");
    assert((ss of Anything) is Singleton<String>);
}
```

produces:

```
$ ceylon run-js simple

/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:2352
$.$ta_=$ta;$_Object(singleton$);Sequence({Element$Sequence:$$targs$$.Element$S
                                                                    ^
TypeError: Cannot read property 'Element$Singleton' of undefined
    at Singleton (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:2352:114)
    at run (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:12:8)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
Wow. I'm surprised this didn't surface earlier.
