### ISSUE TITLE
bug in model loader preventing compilation of SDK

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#546]
When compiling the SDK I now get:

```
[ceylon-compile-js] ceylon compile-js: null
[ceylon-compile-js] java.lang.NullPointerException
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:874)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:761)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.parseTypeParameters(JsonPackage.java:354)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.loadInterface(JsonPackage.java:573)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.loadDeclarations(JsonPackage.java:112)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.getTypeFromJson(JsonPackage.java:815)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.parseTypeParameters(JsonPackage.java:348)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.loadClass(JsonPackage.java:166)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonPackage.loadDeclarations(JsonPackage.java:110)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsonModule.loadDeclarations(JsonModule.java:57)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsModuleSourceMapper.loadModuleFromMap(JsModuleSourceMapper.java:94)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsModuleSourceMapper.resolveModule(JsModuleSourceMapper.java:172)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.loader.JsModuleSourceMapper.resolveModule(JsModuleSourceMapper.java:143)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:91)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:150)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:128)
[ceylon-compile-js] 	at com.redhat.ceylon.compiler.js.CeylonCompileJsTool.run(CeylonCompileJsTool.java:316)
[ceylon-compile-js] 	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
[ceylon-compile-js] 	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
[ceylon-compile-js] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-compile-js] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ceylon-compile-js] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-compile-js] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-compile-js] 	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
[ceylon-compile-js] 	at com.redhat.ceylon.ant.CeylonAntTask.executeCommandline(CeylonAntTask.java:216)
[ceylon-compile-js] 	at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAntTask.java:173)
[ceylon-compile-js] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ceylon-compile-js] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[ceylon-compile-js] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-compile-js] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-compile-js] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ceylon-compile-js] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-compile-js] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-compile-js] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[ceylon-compile-js] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[ceylon-compile-js] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[ceylon-compile-js] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[ceylon-compile-js] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[ceylon-compile-js] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[ceylon-compile-js] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[ceylon-compile-js] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[ceylon-compile-js] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

This is probably the result of changes I made to `ceylon.language`.

**Comment by chochos** [comment]
done

**Comment by gavinking** [comment]
Thanks!
