### ISSUE TITLE
error for constructor extension with type parameter

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#555]
This code
```ceylon
class Foo<F> {
    shared F f;
    shared new Bar(F f){
        this.f = f;
    }
    
    shared new (F f) extends Bar(f){} 
}

shared void run(){
    print(Foo(42).f);
}
```
when executed
```
\org\boo\1.0.0\org.boo-1.0.0.js:16
foo$.f_=$3q;
       ^
TypeError: Cannot set property 'f_' of undefined
    at Foo_Bar$$a (test52\modules\org\boo\1.0.0\org.boo-1.0.0.js:16:8)
    at Foo_$c$ (test52\modules\org\boo\1.0.0\org.boo-1.0.0.js:33:1)
    at Foo (test52\modules\org\boo\1.0.0\org.boo-1.0.0.js:13:31)
    at run (test52\modules\org\boo\1.0.0\org.boo-1.0.0.js:56:12)
    at [eval]:1:283
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
Hm, looking into this I've found a couple of other bugs related to constructors.
