### ISSUE TITLE
IllegalArgumentException + stack trace if model file missing

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#558]
I tried to do `ceylon copy` by hand, and forgot the `-model.js` file. `ceylon compile-js` didn’t like that:

    ceylon compile-js: No such artifact: ceylon.ast.core-1.1.1-model.js
    java.lang.IllegalArgumentException: No such artifact: ceylon.ast.core-1.1.1-model.js
    	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getLeafNode(AbstractNodeRepositoryManager.java:388)
    	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getArtifactResult(AbstractNodeRepositoryManager.java:167)
    	at com.redhat.ceylon.compiler.loader.JsModuleSourceMapper.resolveModule(JsModuleSourceMapper.java:155)
    	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
    	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:91)
    	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:150)
    	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:128)
    	at com.redhat.ceylon.compiler.js.CeylonCompileJsTool.run(CeylonCompileJsTool.java:316)
    	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
    	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
    	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
    	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
    	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)

That should probably be a proper error message.

**Comment by quintesse** [comment]
You did a `ceylon copy` but it didn't copy the `-model.js` file?? If that's true it would be a bug in `ceylon copy`

**Comment by lucaswerkmeister** [comment]
> I tried to do `ceylon copy` by hand

Meaning that I couldn’t figure out how to do `ceylon copy` (what’s the special syntax for `USER`? I didn’t want a `USER` dir in my cdw :D), and instead did

    cp modules/ceylon/ast/core/1.1.1/ceylon.ast.core-1.1.1.js* ~/.ceylon/repo/ceylon/ast/core/1.1.1/

which didn’t include the `-model.js` file.

**Comment by quintesse** [comment]
Aaah ok :)

> what’s the special syntax for USER?

See `ceylon copy --help`

and for more detailed info: http://www.ceylon-lang.org/documentation/1.1/reference/tool/config/#_repository_sections
