### ISSUE TITLE
Callable ref of non default constructor undefined

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#564]
When this code is executed
```ceylon
shared void run(){
    class Foo{ 
        shared new Bar(){} 
    }
    (Foo.Bar)();
}
```
```
ReferenceError: Bar is not defined
    at run (modules\org\boo\1.0.0\org.boo-1.0.0.js:34:1)
    at [eval]:1:283
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
huh, this only happens when `Foo` is inside `run`; if works when `Foo` is toplevel.
