### ISSUE TITLE
errors with curry (flatten/unflatten?) & Sequentials

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#568]
Passing `Sequential`s to functions created with `curry` causes runtime errors *if* it is not statically known that a `Sequential` will be used. Note that in the code below, `curry` and `uncurry` are used without static knowledge of `Sequential`.

There are two errors that seem to be related:

```ceylon
object listUtils {
    shared List<B>(List<A>) lift<A, B>(B(A) f)
        =>  curry(map<A,B>)(f);

    shared List<B> map<A,B>(B(A) f, List<A> list)
        =>  list.collect(f); 

    shared List<Integer> double(List<Integer> list)
        =>  uncurry(List<Integer>.collect<Integer>)(list,2.times);
}

shared void breakIt() {
    value double = listUtils.lift(2.times);
    print(double(Array {1,2,3}));       // works
    print(double([1,2,3]));             // error #1
    print(listUtils.double([1,2,3]));   // error #2
}
```
Error 1:
```
/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:185
return $20bb.collect($20ba,{Result$collect:$uxljvo$.B$map});};
             ^
TypeError: Object 1 has no method 'collect'
    at $init$listUtils$core.listUtils$.$_map (/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:185:14)
    at Function.JsCallable.f2 (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:666:10)
    at ru (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:4214:11)
    at $JsCallable.nm (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3292:668)
    at rf (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3402:8)
    at breakIt$core (/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:213:14)
    at [eval]:1:342
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
```

Error 2:
```
/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:662
if (f.jsc$)f=f.jsc$;
     ^
TypeError: Cannot read property 'jsc$' of undefined
    at Object.JsCallable (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:662:6)
    at Number.m$1znx.uncurry.m$1znx.$JsCallable.nm (/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:189:68)
    at f (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:647:11)
    at $JsCallable.nm (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3293:106)
    at rf (/Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150526-1959/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3404:8)
    at $init$listUtils$core.listUtils$.$_double (/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:189:1042)
    at breakIt$core (/Users/jvasileff/Dropbox/Repos/jv/functional-ceylon/modules/test/com/vasileff/fc/0.0.1/test.com.vasileff.fc-0.0.1.js:213:31)
    at [eval]:1:342
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
```

**Comment by chochos** [comment]
Yeah the problem is probably with `flatten` or `unflatten`

**Comment by chochos** [comment]
After much digging, this problem seems to be in the compiler after all. I mean `flatten` and `unflatten` _were_ broken anyway, but I just noticed that the runtime model is wrong for the parameters of static method refs, such as `List<Integer>.collect<Integer>` - the argument to that must be a `List<Integer>`, not an `Integer(Integer)` (which is the parameter of `collect`).

**Comment by chochos** [comment]
This particular issue has been fixed.
