### ISSUE TITLE
TypeError returning optional instance of dynamic interface

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#571]
```ceylon
dynamic JSMath {
    shared formal Float abs(Float x);
}

JSMath? jsMath {
    dynamic { return Math; }
}

shared
void run() {
    print(jsMath?.abs(10.0));
}
```
produces:
```
$ ceylon compile-js && ceylon run-js simple
Note: Created module simple/1.0.0

/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:28
$2,m$1.mut$([{t:m$1.Null},{t:$init$JSMath()}]))?$2:function(){throw new TypeEr
                                                                    ^
TypeError: Expected ceylon.language::Null|simple::JSMath (run.ceylon 6:21-6:24)
    at /private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:28:197
    at jsMath (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:28:283)
    at run (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:37:15)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

Returning `JSMath` (non-optional) works.

**Comment by chochos** [comment]
If `jsMath` if of type `JsMath` then its declaration is dynamic; if it's of type `JsMath?` then it's a union type and its declaration is *not* dynamic.

Seems I have to check if the type is a union or intersection and if any of its components contain a dynamic declaration, instead of just directly checking if the declaration is dynamic.
