### ISSUE TITLE
`undefined` error when using `completeCompilationUnit` value

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#574]
```ceylon
module tmp "1.0.0" {
    shared import ceylon.ast.samples "1.1.1";
}

import ceylon.ast.samples.completeCompilationUnit { completeCompilationUnit }
shared void run() {
    value v = completeCompilationUnit;
}
```
> tmp-1.0.0.js:16
```js
var $3=m$2.completeCompilationUnit$ceylon$ast$samples$completeCompilationUnit(
           ^
```
TypeError: undefined is not a function
    at run (…/tmp-1.0.0.js:16:12)
    at [eval]:1:273
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3

[generated code](https://gist.github.com/lucaswerkmeister/65d004c4b3fa87465202)

**Comment by lucaswerkmeister** [comment]
I haven’t been able to reproduce this with values from other modules so far.

**Comment by lucaswerkmeister** [comment]
`completeCompilationUnit` is defined [here](https://github.com/ceylon/ceylon.ast/blob/0124da5fed0576e67e701a19869d92ca46a219a6/source/ceylon/ast/samples/completeCompilationUnit/completeCompilationUnit.ceylon#L248) and used [here](https://github.com/ceylon/ceylon.ast/blob/0124da5fed0576e67e701a19869d92ca46a219a6/source/test/ceylon/ast/core/Editor.ceylon#L26). The bug can also be reproduced by running `ant test-js` in `ceylon.ast` (though then the exception is wrapped in a `NativeError`).

**Comment by lucaswerkmeister** [comment]
`ceylon.parse` seems to have the same error: when running `ceylon compile-js '*'; ceylon test-js test.ceylon.parse`, two tests (`broadGeneric`, `sequence`) fail with “undefined is not a function”.

**Comment by chochos** [comment]
I can't compile `ceylon.ast`

**Comment by lucaswerkmeister** [comment]
Weird, `ant clean test-js` works here

**Comment by chochos** [comment]
I had to manually compile core and its tests but I managed to get the error now.

**Comment by lucaswerkmeister** [comment]
What error did you get?

**Comment by chochos** [comment]
It's a different one, the problem is it couldn't find the `samples` module (because I didn't compile it). But I get errors trying to compile that one as well as the `redhat` module, on CLI.

**Comment by chochos** [comment]
Ah, found it! The module `ceylon.ast.samples` has no root package, and that causes the wrong name to be generated. Just running some tests before I push the fix...

**Comment by lucaswerkmeister** [comment]
Thanks! I’m still getting an error, but now it seems to be a different one:
```
$ ceylon run-js --run=test.ceylon.ast.core::testEditor test.ceylon.ast.core
/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:549
if (lt[i].t===iu) {
         ^
TypeError: Cannot read property 't' of undefined
    at flattentype$ (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:549:10)
    at mut$ (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:561:7)
    at ChainedIterator (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3725:80)
    at that.iterator (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1165:8)
    at m$1.tpl$.m$1.for$.Element$Iterable [as makeNextFunc] (/home/lucas/git/ceylon/ceylon.ast/modules/ceylon/ast/core/1.1.1/ceylon.ast.core-1.1.1.js:11472:25)
    at for$$proto.iterator (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1018:22)
    at Object.tpl$ (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1109:22)
    at node$.transformChildren (/home/lucas/git/ceylon/ceylon.ast/modules/ceylon/ast/core/1.1.1/ceylon.ast.core-1.1.1.js:11471:12)
    at node$.visitChildren (/home/lucas/git/ceylon/ceylon.ast/modules/ceylon/ast/core/1.1.1/ceylon.ast.core-1.1.1.js:11487:14)
    at visitor$.visitNode (/home/lucas/git/ceylon/ceylon.ast/modules/ceylon/ast/core/1.1.1/ceylon.ast.core-1.1.1.js:12679:13)
```
Should I report that as a separate bug?

**Comment by chochos** [comment]
I did see that one, but I think it may be due to the ast samples module not being complete – I just can't get it to compile for JS, and the tests use it but since it's incomplete, that may be the cause for the error...

**Comment by lucaswerkmeister** [comment]
Oh, now I get the error you’re mentioning as well – but only when running `ceylon compile ceylon.ast.samples`, not with `ant clean compile-js`. Very strange…

**Comment by lucaswerkmeister** [comment]
#579, a model loader issue

**Comment by lucaswerkmeister** [comment]
Okay, #579 is fixed, and I’m still getting that other `undefined` error. No compiler errors in `ant clean test-js`.

**Comment by chochos** [comment]
no, this is a bug in native code.
