### ISSUE TITLE
dynamic blocks & type errors with numbers

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#576]
Performing numerical calculations in dynamic blocks can result in TypeErrors, even with partial type information:

```ceylon
    Float result;
    dynamic {
        Float n = Math.log(100.0);
        result = n / Math.\iLN10;
    }        
```
produces:
```
com.vasileff.ceylon.xmath-0.0.1.js:1173
:Math).LN10),typeof($8b)==='number'?m$1.Float($8b):function(){throw new TypeEr
                                                                    ^
TypeError: Expected Float (TESTING.ceylon 45:17-45:29)
    at $88 (/Users/jvasileff/Dropbox/Repos/jv/ceylon-xmath/modules/com/vasileff/ceylon/xmath/0.0.1/com.vasileff.ceylon.xmath-0.0.1.js:1173:198)
    at run (/Users/jvasileff/Dropbox/Repos/jv/ceylon-xmath/modules/com/vasileff/ceylon/xmath/0.0.1/com.vasileff.ceylon.xmath-0.0.1.js:1173:259)
    at [eval]:1:339
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

```

but this works:

```ceylon
    Float result;
    dynamic {
        Float n = Math.log(100.0);
        Float d = Math.\iLN10;
        result = n / d;
    }
```

**Comment by jvasileff** [comment]
Hmm, sometimes there isn't a TypeError, but just a bad result. This is similar to #575, returning an Integer:

```ceylon
shared native("js")
Float hypot(Float x, Float y) {
    if (x.infinite || y.infinite) {
        return infinity;
    }
    else if (x.undefined || y.undefined) {
        return undefined;
    }
    else {
        dynamic {
            // Really help out the js compiler
            // https://github.com/ceylon/ceylon-js/issues/576
            Float x2 = Math.pow(x, 2);
            Float y2 = Math.pow(y, 2);
            Float x2y2 = x2 + y2;
            return Math.sqrt(x2y2);
            //return result;
            //Float result = Math.sqrt(x2y2);
            //return result;
        }
    }
}
```

**Comment by chochos** [comment]
So this is something that also happens with `Integer`s?

**Comment by jvasileff** [comment]
I meant that `hypot`, as is, returns `Integer`s, without producing an error.

By commenting out the `return`, and uncommenting:
```ceylon
            //Float result = Math.sqrt(x2y2);
            //return result;
```

the result is always a `Float`.

**Comment by chochos** [comment]
I found out why this happens with `Float`s, but I'm not sure it happens with `Integer`s, that's why I asked. Fix coming up soon.

**Comment by jvasileff** [comment]
Oh, I see. I'll keep an eye out for the reverse.
