### ISSUE TITLE
Error with `Array(1..4).keys.reversed`

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#619]
```ceylon
value foo = Array(1..4).keys.reversed;
```

gives

```
/opt/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150823-2253/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3601
']};});atr$(list$,'reversed',function(){var list$=this;return list$.Reversed$L
                                                                    ^
TypeError: Object [object Object] has no method 'Reversed$List'
    at $init$List.atr$.mod [as reversed] (/opt/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150823-2253/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3601:932)
    at run (/home/tschotan/projects/ceylon/eclipse-workspace/JsTests/modules/test1/1.0.0/test1-1.0.0.js:13:106)
    at [eval]:1:279
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```

**Comment by quintesse** [comment]
Hmmm, now that I take a proper look at the error I imagine it's more an issue for the language module.

**Comment by quintesse** [comment]
Indeed, moved to https://github.com/ceylon/ceylon.language/issues/733 . Closing.
