### ISSUE TITLE
Error running language tests

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#626]
```
[ceylon-run-js] /home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:11030
[ceylon-run-js] inedIterator,'CycledIterator':CycledIterator,'$prop$getNullElement':$1iq,'null
[ceylon-run-js]                                                                     ^
[ceylon-run-js] ReferenceError: $1iq is not defined
[ceylon-run-js]     at /home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:11030:142
[ceylon-run-js]     at /home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:11034:37
[ceylon-run-js]     at /home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1:83
[ceylon-run-js]     at Object.<anonymous> (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:11033:2)
[ceylon-run-js]     at Module._compile (module.js:456:26)
[ceylon-run-js]     at Object.Module._extensions..js (module.js:474:10)
[ceylon-run-js]     at Module.load (module.js:356:32)
[ceylon-run-js]     at Function.Module._load (module.js:312:12)
[ceylon-run-js]     at Module.require (module.js:364:17)
[ceylon-run-js]     at require (module.js:380:17)
```

**Comment by lucaswerkmeister** [comment]
Weird, it’s called `$1ik` in my error messages.

**Comment by lucaswerkmeister** [comment]
And it seems to happen for every JS program, even an empty `run` function.

**Comment by quintesse** [comment]
There's a method `getRandomIdentifierPostfix()` there somewhere for sure ;)

**Comment by FroMage** [comment]
@chochos this is super urgent. Nobody can run anything on JS anymore.

**Comment by chochos** [comment]
Somebody please confirm if this is running ok for you guys now and close it, or let me know if you still can't run anything.

**Comment by lucaswerkmeister** [comment]
Works for me.
