### ISSUE TITLE
Error taking reference to identity function

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#627]
This is the last of the JS errors I have been trying to reproduce, which I've narrowed down to:

```ceylon
interface Monad<Box> {
    shared void join(Box source) {
        value x = identity<Box>;
    }
}

object singletonTypeClass satisfies Monad<Singleton<Anything>> {}

shared void run() {
    singletonTypeClass.join(Singleton(Singleton(1)));
}
```
producing:
```
var $vw4=m$vvx.JsCallable(monad$,m$vvx.identity,{Value$identity:$$targs$$.Box$
                                                                ^
ReferenceError: $$targs$$ is not defined
    at $init$Monad.monad$.$_join (/Users/jvasileff/Dropbox/Repos/jv/simple/modules/simple/1.0.0/simple-1.0.0.js:41:65)
    at run (/Users/jvasileff/Dropbox/Repos/jv/simple/modules/simple/1.0.0/simple-1.0.0.js:74:22)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
hm, same thing as with #624 (which was fixed in a very different way)
