### ISSUE TITLE
Runtime error with abbreviated Tuple syntax

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#631]
Using `Integer[2]` as a type argument to `map` results in a runtime error:

```ceylon
        {Integer[2]*} a1 = [[1,1]].map<Integer[2]>       ((Integer[2] x) => x); // error
        {Integer[2]*} a2 = [[1,1]].map<[Integer,Integer]>((Integer[2] x) => x); // ok
        {Integer[2]*} a3 = [[1,1]].map                   ((Integer[2] x) => x); // ok

```
produces
```
var $i7o=(2)m$hzl.tpl$([m$hzl.tpl$([1,1])]).$_map(m$hzl.$JsCallable((function(
            ^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:85
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

**Comment by chochos** [comment]
Good catch. I had only implemented this in declarations such as `Integer[2] = [1,2]`
