### ISSUE TITLE
iterable weirdness

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#634]
I'm guessing this is new:

```ceylon
shared void run() {
  print({ 1, 2 }.filter((Integer x) => true));          // prints "1"
  print({ 1, 2 }.filter((Integer x) => true).sequence()); // error
}
```
console:
```
jvasileff@orion:simple$ ceylon compile-js simple && ceylon run-js simple
Note: Created module simple/1.0.0
1

/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:12
le:m$1.mtt$([{t:m$1.Integer}]),Return$Callable:{t:m$1.$_Boolean}})).sequence()
                                                                    ^
TypeError: Object 1 has no method 'sequence'
    at run (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:12:218)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by chochos** [comment]
I realize this is a bug, but still... is using `sequence` instead of `sequence()` on purpose?

**Comment by jvasileff** [comment]
Ah, no, good catch. I updated the description to add the `()`.

**Comment by chochos** [comment]
I just ran this with `sequence` and got `JsCallable` string; with `sequence()` I get `[1,2]`

**Comment by jvasileff** [comment]
Huh, so I guess you also get `{1, 2}` for the first one. I'm running a build from Monday night, but can try again once I update.

**Comment by chochos** [comment]
So, were you able to reproduce this?

**Comment by jvasileff** [comment]
I haven't recompiled yet. I'll try now.

**Comment by jvasileff** [comment]
@chochos sorry, this works perfectly well with a fresh build.
