### ISSUE TITLE
js tests failing

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#636]
The tests fail with this error:

```
    [junit] /Users/gavin/ceylon.language/build/toolsTest/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:4227
    [junit] $oivar $ok;if(is$(($ok=$ol()),{t:List,a:{Element$List:{t:Anything}}})){if((($o
    [junit]        ^^^
    [junit] SyntaxError: Unexpected identifier
    [junit]     at exports.runInThisContext (vm.js:73:16)
    [junit]     at Module._compile (module.js:443:25)
    [junit]     at Object.Module._extensions..js (module.js:478:10)
    [junit]     at Module.load (module.js:355:32)
    [junit]     at Function.Module._load (module.js:310:12)
    [junit]     at Module.require (module.js:365:17)
    [junit]     at require (module.js:384:17)
    [junit]     at /Users/gavin/ceylon.language/build/toolsTest/modules/modules/hello/1/modules.hello-1.js:5:9
    [junit]     at /Users/gavin/ceylon.language/build/toolsTest/modules/modules/hello/1/modules.hello-1.js:17:37
    [junit]     at /Users/gavin/ceylon.language/build/toolsTest/modules/modules/hello/1/modules.hello-1.js:1:83
```

I've also experienced the same error in the IDE.

**Comment by chochos** [comment]
This is due to `GuardedVariable`. I pushed a patch to avoid this problem, although it's far from being an optimal solution.
