### ISSUE TITLE
Can't test SDK

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#644]
```
[ceylon-test-js] NODE_PATH=/home/stephane/src/java-eclipse/ceylon-dist/dist/repo:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/test-deps:/home/stephane/.ceylon/repo:/home/stephane/.ceylon/cache:[Maven] Aether:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/modules
[ceylon-test-js] 
[ceylon-test-js] /home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:637
[ceylon-test-js] tingTypeProto($JsCallable, Function, 'ceylon.language::JsCallable', Callable);
[ceylon-test-js]                                                                     ^
[ceylon-test-js] ReferenceError: Callable is not defined
[ceylon-test-js]     at /home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:637:77
[ceylon-test-js]     at /home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:5597:37
[ceylon-test-js]     at /home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1:83
[ceylon-test-js]     at Object.<anonymous> (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:5596:2)
[ceylon-test-js]     at Module._compile (module.js:456:26)
[ceylon-test-js]     at Object.Module._extensions..js (module.js:474:10)
[ceylon-test-js]     at Module.load (module.js:356:32)
[ceylon-test-js]     at Function.Module._load (module.js:312:12)
[ceylon-test-js]     at Module.require (module.js:364:17)
[ceylon-test-js]     at require (module.js:380:17)
[ceylon-test-js] ceylon test-js: Node process exited with non-zero exit code: 8
```

That sounds like a JS issue more than a test issue.

**Comment by FroMage** [comment]
Apparently the language module does not contain enough info. Something must have gone wrong during stitching? There's no `function Callable` like there is for other interfaces.

**Comment by FroMage** [comment]
I'll try to find out why

**Comment by lucaswerkmeister** [comment]
Doesn’t have anything to do with the SDK, this also happens when trying to run a trivial “hello, world” program.

**Comment by FroMage** [comment]
OK it's caused by 0e0b13c7e6e1b16618b87113e93e62601b48e3ce

**Comment by FroMage** [comment]
So it turns out we have errors for missing native stuff, that are never displayed and do not count as failures.

**Comment by quintesse** [comment]
Pfff :(

**Comment by FroMage** [comment]
OK I have pushed a fix that lets us run the language tests. I'll leave open for you guys to check it, as I know how the language module stitching works, but no idea if this is also valid for normal module's native stuff.

**Comment by quintesse** [comment]
Well I'm not too familiar myself either but it looks good to me. Btw, the "rules" for stitching are compiled here by @chochos : https://github.com/ceylon/ceylon-js/wiki/Native-Compilation

**Comment by chochos** [comment]
That last commit was completely useless I think. But still, you guys fixed this.
