### ISSUE TITLE
SDK test fails on JS

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#647]
```
[ceylon-test-js] running: test.ceylon.test.suite::testAssertEquals
[ceylon-test-js] ceylon.language::AssertionError "assertion failed: expected exception with message assertion failed: expected <[]> but was <{ 1, 2, 3 }>, but has assertion failed: expected <[]> but was <[1, 2, 3]>"
[ceylon-test-js]     at Object.AssertionError (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:4932:1)
[ceylon-test-js]     at $init$ExceptionAssert.exceptionAssert$.hasMessage (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.2.0/ceylon.test-1.2.0.js:163:23)
[ceylon-test-js]     at testAssertEquals (/home/stephane/src/java-eclipse/ceylon-sdk/modules/test/ceylon/test/suite/1.2.0/test.ceylon.test.suite-1.2.0.js:905:421)
[ceylon-test-js]     at Function.$init$AppliedFunction$jsint.appliedFunction$.$_apply (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:8917:15)
[ceylon-test-js]     at $init$FunctionalDeclaration$meta$declaration.functionalDeclaration$.invoke (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:6015:101)
[ceylon-test-js]     at $init$DefaultTestExecutor$core.defaultTestExecutor$.$wgb9lg$3ij (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.2.0/ceylon.test-1.2.0.js:1935:6)
[ceylon-test-js]     at Number.$3ix (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.2.0/ceylon.test-1.2.0.js:1892:22)
[ceylon-test-js]     at c2 (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:690:10)
```

The same works for JVM, so I assume it's a JS bug, or perhaps a metamodel bug.

**Comment by chochos** [comment]
perhaps something to do with tuples...

**Comment by chochos** [comment]
or, I did change some stuff to return ArraySequence instead of a simple Array, but I don't see how that would be related to this.

**Comment by FroMage** [comment]
Lemme see if I can narrow it down.

**Comment by FroMage** [comment]
So what happens is that `{1,2,3}.string == "[1, 2, 3]"` on JS now. That's gotta be new and a mistake, no?

**Comment by FroMage** [comment]
OK found it, it's indeed due to #642. I can fix it for `Tree.SequenceEnumeration` I suppose.
