### ISSUE TITLE
incorrect result with flatten, spread

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#649]
The program below outputs `1` on JS, but should output `55`. This also fails on an old 2015-06-25 version of Ceylon.

It's a bit complex, and I can help to reduce it later, but wanted to at least open the issue now.

```ceylon
shared void run() {
  Return(*Arguments) fix<Return, Argument, Arguments>(
          Return(*Tuple<Return(*Arguments)|Argument,
                        Return(*Arguments),
                        Arguments>) f)
          given Arguments satisfies Argument[]
      =>  flatten((Arguments args)
          =>  f(fix(f), *args));
          // JVM needs the curry version; both produce the same results js
          //=>  curry(f)(fix(f))(*args));

  value fibonacci2
      =   fix((Integer(Integer, Integer, Integer) recurse,
                  Integer x, Integer a=0, Integer b=1)
          =>  if (x > 2) then recurse(x - 1, b, a + b) else (a + b));

  print (fibonacci2(10));
}
```

**Comment by jvasileff** [comment]
So the problem is that the runtime `x` for `Integer x` winds up being a `Tuple` of type `[ceylon.language::Integer,ceylon.language::Null,ceylon.language::Null]` rather than an `Integer`. I guess in JS `(x > 2)` evaluates to false for non-numeric `x`.

A slightly simpler reproduction:

```ceylon
    Return(*Arguments) stripStringParam<Return, Argument, Arguments>
            (Return(*Tuple<String|Argument, String, Arguments>) f)
            given Arguments satisfies Argument[]
        =>  flatten((Arguments args) => f("", *args));

    Integer(Integer) fn = stripStringParam((String s, Integer i) => i);
    print(type(fn(1))); // [ceylon.language::Integer]
```

**Comment by jvasileff** [comment]
A further problem is that making `i` optional:

```ceylon
    Integer(Integer=) fn = stripStringParam((String s, Integer i=1) => i);
```

results in a runtime error:

```
TypeError: detpl$ requires a proper Tuple {t:Tuple,a:{First$Tuple:F,Element$Tuple:E,Rest$Tuple:R}}
    at detpl$ (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:1586:7)
    at Object.flatten (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:4219:4)
    at $b (/Users/jvasileff/Dropbox/Repos/jv/simple/modules/simple/1.0.0/simple-1.0.0.js:21:41)
    at run (/Users/jvasileff/Dropbox/Repos/jv/simple/modules/simple/1.0.0/simple-1.0.0.js:23:8)
    at [eval]:1:282
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
ceylon run-js: Node process exited with non-zero exit code: 1
```

**Comment by chochos** [comment]
weird, this doesn't even compile in JVM

**Comment by chochos** [comment]
@jvasileff can you compile this on JVM?

**Comment by jvasileff** [comment]
hmm, I can only compile the simplified example on JVM with the `curry` workaround from the original example:

```ceylon
        //=>  flatten((Arguments args) => f("", *args));
        =>  flatten((Arguments args) => curry(f)("")(*args));
```

but written this way, the JS bug doesn't occur. The bug *does* occur for me on JS for the first example with or without the curry workaround.

**Comment by jvasileff** [comment]
I filed the JVM bug as https://github.com/ceylon/ceylon-compiler/issues/2377
