### ISSUE TITLE
runtime error if native impl precedes header with default

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#652]
For:

```ceylon
native("jvm") class NC() {}
native("js") class NC() {}

native class NC() {
    shared void foo() => print("default impl");
}

shared void run() {
    NC().foo();
}
```

you get:

```
$ ceylon compile-js && ceylon run-js simple
Note: Created module simple/1.0.0

/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:26
NC().foo();
     ^
TypeError: Object [object Object] has no method 'foo'
    at run (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:26:6)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
ceylon run-js: Node process exited with non-zero exit code: 8
jvasileff@orion:simple$ 
```

This corresponds to https://github.com/ceylon/ceylon-compiler/issues/2367

**Comment by quintesse** [comment]
I actually don't think these are backend errors but something we should prohibit in the typechecker.

**Comment by chochos** [comment]
well the problem is with the forward declaration, so it sounds like something to deal with in the backend.

But I can't figure out what's harder: compiling this or marking an error.

**Comment by chochos** [comment]
nevermind.

**Comment by chochos** [comment]
this shit doesn't work at all.

**Comment by quintesse** [comment]
This has been fixed incorrectly, will revert and fix it in the typechecker under this issue: https://github.com/ceylon/ceylon-spec/issues/1446
