### ISSUE TITLE
default member class implementations for natives neither disallowed nor supported

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#653]
```ceylon
native class NC4() {
    shared class Inner() {
        shared void foo() => print("hello");
    }
}

native("js") class NC4() {}
native("jvm") class NC4() {}

shared void run() {
    NC4().Inner().foo();
}
```
results in the runtime error:
```
$ ceylon compile-js && ceylon run-js simple
Note: Created module simple/1.0.0

/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:26
NC4().Inner$NC4().foo();
      ^
TypeError: Object [object Object] has no method 'Inner$NC4'
    at run (/private/tmp/simple/modules/simple/1.0.0/simple-1.0.0.js:26:7)
    at [eval]:1:282
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
ceylon run-js: Node process exited with non-zero exit code: 8
jvasileff@orion:simple$ 
```
This corresponds to https://github.com/ceylon/ceylon-compiler/issues/2368

**Comment by chochos** [comment]
the fix for this is in `NativeUtil` which is in ceylon/ceylon-spec

**Comment by gavinking** [comment]
What is the status of this issue? I take it that this is something that @chochos needs to implement support for? It's not clear from the issue description.

**Comment by chochos** [comment]
I added initial support but it's not a real fix, @quintesse and I are looking into it.

**Comment by quintesse** [comment]
I fixed this in several places and I don't see any errors in the JS tests so I guess this is fixed now here too :)
