### ISSUE TITLE
support direct invocations on grouped expressions

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#659]
Direct invocations on grouped expressions do not currently work:

```ceylon
shared void run() {
    value a = ("hello ".plus) { "world"; };   
    value b = (("hello ".plus)) { "world"; }; 
    value c = 1.plus { 2; };        
    value d = (1.plus) { 2; };      
    value e = ((1.plus)) { 2; };    
    //value f = (Singleton)(10);

    print ({a,b,c,d,e});
}
```
prints:
```
{ ceylon.language::JsCallable@1, ceylon.language::JsCallable@2, 3, ceylon.language::JsCallable@3, ceylon.language::JsCallable@4 }
```
Uncommenting the `value f` line results in:
```
/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:5189
$1an_=$1an;$_Object(singleton$);Sequence({Element$Sequence:$$targs$$.Element$S
                                                                    ^
TypeError: Cannot read property 'Element$Singleton' of undefined
    at Object.Singleton (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:5189:80)
    at run (/Users/jvasileff/Dropbox/Repos/jv/simple/modules/simple/1.0.0/simple-1.0.0.js:36:12)
```
See also https://github.com/ceylon/ceylon-spec/issues/1449

**Comment by chochos** [comment]
But this is a new feature, right?

**Comment by gavinking** [comment]
It's not new, but I now think the typechecker should actually disallow all these things.

**Comment by gavinking** [comment]
[Moved.](https://github.com/ceylon/ceylon-spec/issues/1467)
