### ISSUE TITLE
type problems using FunctionDeclaration.invoke()

### ISSUE THREAD

**Issue by dseebacher** [ceylon/ceylon-js#666]
I can't use `invoke()` with generic parameters:

```ceylon
shared void run() {
	foo([1]);
}

void foo(List<Integer> l) {
	`function bar`.invoke([], l);
}

void bar(List<Integer> l) {
	print("v: ``l``");
}
```
and here the output:
```
$ ceylon compile-js js.error_invoke && ceylon run-js js.error_invoke
Note: Created module js.error_invoke/1.0.0

/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:7038
if (a[i]!==undefined && !is$(a[i],val_t))throw IncompatibleTypeException$meta$
                                               ^
ceylon.language.meta.model::IncompatibleTypeException "Wrong type for argument 0, expected ceylon.language::List<ceylon.language::Integer> got ceylon.language::Integer"
ceylon run-js: Node process exited with non-zero exit code: 8
```

while on the jvm:
```
$ ceylon compile js.error_invoke && ceylon run js.error_invoke
Note: Created module js.error_invoke/1.0.0
v: [1]
```

A second example:
```ceylon
shared void run() {
	foo([1]);
}

void foo(Alias l) {
	`function bar`.invoke([], l);
}

void bar(Alias l) {
	print("v: ``l``");
}

interface Alias => List<Integer>;
```
and the output:
```
$ ceylon compile-js js.error_invoke_alias && ceylon run-js js.error_invoke_alias
Note: Created module js.error_invoke_alias/1.0.0

/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:525
for (t in t1.t.$$.T$all) {
                 ^
TypeError: Cannot read property 'T$all' of undefined
    at extendsType (/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:525:18)
    at convert$params (/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:7002:22)
    at Function.$init$AppliedFunction$jsint.appliedFunction$.$_apply (/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:8917:3)
    at $init$FunctionalDeclaration$meta$declaration.functionalDeclaration$.invoke (/usr/lib/ceylon/1.2.0/repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:6023:101)
    at foo (/ceylon/CeylonTests/modules/js/error_invoke_alias/1.0.0/js.error_invoke_alias-1.0.0.js:14:67)
    at run (/ceylon/CeylonTests/modules/js/error_invoke_alias/1.0.0/js.error_invoke_alias-1.0.0.js:9:1)
    at [eval]:1:327
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
ceylon run-js: Node process exited with non-zero exit code: 8
```
and again on the jvm:
```
$ ceylon compile js.error_invoke_alias && ceylon run js.error_invoke_alias
Note: Created module js.error_invoke_alias/1.0.0
v: [1]
```

**Comment by gavinking** [comment]
Ouch. @chochos I guess we need to roll the fix for this into 1.2.1.

**Comment by dseebacher** [comment]
As it might take a little to get released, is there any other way to call a function with at compile time unknown type parameters e.g: ``` `function bar`.invoke([CalculatedType], ...)``` ?

**Comment by chochos** [comment]
Sorry about the delay. I'll take a look today, it's probably some trivial bug.

**Comment by gavinking** [comment]
Mark of the beast!

**Comment by chochos** [comment]
Yeah, I was expecting this particular issue to be something really evil.

**Comment by dseebacher** [comment]
@chochos The second example still does not work for me, is it related to any other open issue?

**Comment by chochos** [comment]
Ah, didn't check that one. That's a separate issue, related to aliases, but I don't think it's been filed yet. I'll open it.
